sut:
  build: .
  command: apk add --no-cache bash && bash -c 'sleep 15 && ./unittest.sh'
  links:
    - "mysql"
    - "memcached"

  environment:
    - DB_HOST=database
    - MEMCACHED_ADDRESS=memcached

mysql:
  image: mysql:5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=portal
  ports:
    - "3306:3306"

memcached:
  image: memcached:alpine
  ports:
    - "11211:11211"
